name: Publish to Pypi
on:
  release:
    types: [created]

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
    - name: Check version
      run: echo $RELEASE_VERSION
    - name: Set version
      run: sed -i -- "s/<RELEASE_VERSION>/$RELEASE_VERSION/g" pyproject.toml
    - name: Build
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: 3.7.4
        poetry_version: 1.0
        args: build
    - name: Publish to Pypi
      uses: abatilo/actions-poetry@v1.5.0
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      with:
        python_version: 3.7.4
        poetry_version: 1.0
        args: publish -u $PYPI_USERNAME -p $PYPI_PASSWORD
