name: Publish to Pypi
on:
  release:
    types: [created]

jobs:
  publish:
    strategy:
      fail-fast: true
      matrix:
        python-version: [3.7]
        poetry-version: [1.0.10]
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Setup dependencies
        run: poetry install
      - name: Build
        run: poetry build
      - name: Publish to Pypi
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: poetry publish -u $PYPI_USERNAME -p $PYPI_PASSWORD
